/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Post = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });

export const idlService = IDL.Service({
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'getPost' : IDL.Func([IDL.Text], [Post], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'post' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Post = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  
  return IDL.Service({
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'getPost' : IDL.Func([IDL.Text], [Post], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'post' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };